import assert from "node:assert/strict";
import { withProfileHarness } from "./profile_harness.mjs";
// Sync rows sit below the fold of a lazily built list, so results are revealed
// by real scrolling before they are asserted.
await withProfileHarness(process.argv[2] ?? "web", "sync", async ({ steps, labels, reveal, tap, toggle, wait, capture, theme }) => {
  await wait("A little room for good ideas");
  await tap("Preferences"); await wait("Appearance");
  await reveal("Preference sync is not set up"); await capture("sync-unset-light");
  assert.ok(!(await labels()).includes("Apply a saved profile first"));
  await reveal("Keep in sync", {button:true}); await tap("Keep in sync");
  await reveal("Paused on this device"); await capture("sync-paused-light");
  steps.push("sync-seeded-paused");
  await reveal("Sync preferences"); await toggle("Sync preferences");
  await reveal("Not synced yet");
  await reveal("Sync now", {button:true}); await tap("Sync now");
  await reveal("reply was lost"); await capture("sync-lost-receipt-dark");
  steps.push("sync-lost-receipt");
  await reveal("Sync now", {button:true}); await tap("Sync now");
  await reveal("Last sync:");
  assert.ok(!(await labels()).includes("reply was lost"));
  await capture("sync-receipt-retry-dark");
  steps.push("sync-receipt-retry");
  await reveal("Tooltips"); await toggle("Tooltips");
  await reveal("Last sync:"); await capture("sync-field-off-dark");
  steps.push("sync-field-choice");
  await theme("Light");
  await reveal("Sync now", {button:true}); await tap("Sync now");
  await reveal("Review 1 preference conflict", {button:true}); await capture("sync-conflict-light");
  await tap("Review 1 preference conflict");
  await wait("Preference conflicts");
  await reveal("Appearance", {button:true}); await tap("Appearance");
  await wait("50 of 52 shared versions reviewed"); await capture("sync-review-first-page-light");
  await reveal("Next versions", {button:true}); await tap("Next versions");
  await wait("52 of 52 shared versions reviewed");
  await reveal("Keep mine", {button:true}); await tap("Keep mine");
  await wait("No preference conflicts are waiting."); await capture("sync-keep-mine-light");
  steps.push("sync-conflict-keep-mine");
  await tap("Back"); await wait("Preferences");
  await theme("Dark");
  await reveal("Sync now", {button:true}); await tap("Sync now");
  await reveal("Review 1 preference conflict", {button:true}); await tap("Review 1 preference conflict");
  await wait("Preference conflicts");
  await reveal("Appearance", {button:true}); await tap("Appearance");
  await wait("50 of 52 shared versions reviewed");
  await reveal("Next versions", {button:true}); await tap("Next versions");
  await wait("52 of 52 shared versions reviewed");
  await reveal("Use profile", {button:true}); await tap("Use profile");
  await wait("No preference conflicts are waiting."); await capture("sync-use-profile-system");
  steps.push("sync-conflict-use-profile");
  await tap("Back"); await wait("Preferences");
  await reveal("Last sync:"); await capture("sync-status-system");
  await tap("Mail"); await wait("A little room for good ideas");
  await capture("sync-mail-preserved");
  steps.push("sync-mail-browsing");
});
