import assert from "node:assert/strict";
import { withProfileHarness } from "./profile_harness.mjs";
await withProfileHarness(process.argv[2] ?? "web", "enrollment", async ({ steps, labels, reveal, tap, wait, capture, theme }) => {
  await wait("A little room for good ideas");
  await tap("Preferences"); await wait("Appearance"); await theme("Light");
  await reveal("Saved Google profiles", {button:true}); await tap("Saved Google profiles");
  await reveal("Find profiles", {button:true}); await tap("Find profiles"); await wait("Profile discovery complete");
  await reveal("Personal", {button:true}); await tap("Personal");
  await wait("Use profile on this device"); await wait("Account connections");
  await capture("enrollment-review-light");
  await reveal("Connection details", {button:true}); await tap("Connection details");
  await wait("mail.example.test:993");
  assert.ok((await labels()).includes("Passwords are entered separately"));
  await capture("enrollment-connection-details-light"); await tap("Close");
  steps.push("enrollment-reviewed-connections");
  await reveal("Apply selected changes", {button:true}); await tap("Apply selected changes");
  await wait("reply was lost"); await capture("enrollment-account-retry-light");
  await reveal("Resume enrollment", {button:true}); await tap("Resume enrollment");
  await wait("Preferences were saved"); await capture("enrollment-settings-retry-dark");
  await tap("Back"); await wait("Profiles and sync"); await tap("Back"); await wait("Preferences");
  await theme("Light");
  await reveal("Saved Google profiles", {button:true}); await tap("Saved Google profiles");
  await reveal("Resume profile review and application", {button:true}); await tap("Resume profile review and application");
  await reveal("Resume enrollment", {button:true}); await tap("Resume enrollment");
  await wait("Profile applied · 2 account connections applied, 0 kept.");
  await capture("enrollment-newer-preference-kept-light");
  steps.push("enrollment-settings-receipt-retry");
  assert.ok((await labels()).includes("2 preferences applied"));
  await capture("enrollment-complete-light");
  steps.push("enrollment-application-retry");
  await reveal("Done", {button:true}); await tap("Done"); await wait("Profiles and sync");
  await tap("Back"); await wait("Preferences");
  await theme("Dark");
  await reveal("Reconnect required");
  assert.ok((await labels()).includes("Saved account"));
  await capture("enrollment-reconnect-dark");
  steps.push("enrollment-reconnect-status");
  await tap("Mail"); await wait("A little room for good ideas");
  await capture("enrollment-mail-preserved-dark");
  steps.push("enrollment-mail-browsing");
});
