#!/usr/bin/env python3
"""Freeze current shared Rust output for the isolated Flutter browser scenario."""
import argparse
import json
import os
from pathlib import Path
import subprocess
ROOT=Path(__file__).resolve().parents[2]
def generate(check=False):
    env=os.environ.copy();env['CARGO_TARGET_DIR']=str(ROOT/'artifacts/root-target')
    source=subprocess.check_output(['cargo','run','--quiet','--locked','-p','shep-mail-content','--example','prepare','--',json.dumps(dict(generation='SHEP-FIXTURE-GENERATION',dark=False,quotes=False))],cwd=ROOT,env=env,input=(ROOT/'shared/html-reader-fixture.eml').read_bytes()).decode()
    value=json.dumps(source,ensure_ascii=True).replace('$',r'\$')
    output='// Generated by scripts/clients/generate_html_fixture.py; test entry only.\n// dart format off\nconst formattedFixtureJson = '+value+';\n'
    target=ROOT/'flutter/test/support/formatted_fixture.dart'
    if check:
        if target.read_text()!=output:raise ValueError('Formatted fixture is stale; rerun generate_html_fixture.py')
    else:target.write_text(output)
if __name__=='__main__':
    parser=argparse.ArgumentParser();parser.add_argument('--check',action='store_true');generate(parser.parse_args().check)
