#!/usr/bin/env python3
"""Keep Flutter test-only fixtures aligned with the browser scenario source."""
import json
from pathlib import Path
root = Path(__file__).resolve().parents[2]
data = json.loads((root / 'shared/preview.json').read_text())
(root / 'flutter/test/support/fixture_json.dart').write_text(
    '// Generated by scripts/clients/generate_fixtures.py; test entry points only.\n'
    + "const fixtureJson = r'''" + json.dumps(data) + "''';\n")
