pub mod backup;
pub mod compose;
pub mod email_content;
pub mod engine;
pub mod fuzzy;
pub mod html_render;
pub mod mail_actions;
pub mod message_find;
pub mod model;
pub mod outgoing;
pub mod providers;
pub mod remote_images;
pub mod replies;
pub mod shortcuts;
pub mod store;
pub mod ui;

#[cfg(feature = "test-support")]
#[path = "../tests/support/fixtures.rs"]
pub mod test_support;
